### PR TITLE
Migrate from jboss-parent to apache parent pom.

### PR DESCRIPTION
**Pull request by baldimir**
- Migrate from jboss-parent to Apache parent pom.

### CODE REVIEW

**Review by lucamolteni — APPROVED** [review]

**Comment by baldimir** [comment]
@lucamolteni do you know please if optaplanner-quickstarts support JDK 17?

**Comment by kie-ci3** [comment]
**PR job** `#2` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-optaplanner/${BRANCH:main}/.ci/buildchain-config.yaml' -o 'bc' -p apache/incubator-kie-optaplanner -u https://github.com/apache/incubator-kie-optaplanner/pull/2992 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-2992/2/display/redirect

**Test results:**
- PASSED: 5121
- FAILED: 19

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-2992/2/testReport/org.acme.kotlin.schooltimetabling.rest/TimeTableResourceTest/solveDemoDataUntilFeasible/">org.acme.kotlin.schooltimetabling.rest.TimeTableResourceTest.solveDemoDataUntilFeasible</a></summary>
java.lang.RuntimeException: Failed to start quarkus
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-2992/2/testReport/org.acme.schooltimetabling.messaging/MessageHandlerTest/solve/">org.acme.schooltimetabling.messaging.MessageHandlerTest.solve</a></summary>
finishConnect(..) failed: Connection refused: localhost/127.0.0.1:5672
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-2992/2/testReport/org.acme.schooltimetabling.messaging/MessageHandlerTest/badRequest_DLQ/">org.acme.schooltimetabling.messaging.MessageHandlerTest.badRequest_DLQ</a></summary>
finishConnect(..) failed: Connection refused: localhost/127.0.0.1:5672
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-2992/2/testReport/org.acme.maintenancescheduling.rest/MaintenanceScheduleResourceTest/solveDemoDataUntilFeasible/">org.acme.maintenancescheduling.rest.MaintenanceScheduleResourceTest.solveDemoDataUntilFeasible</a></summary>
java.lang.RuntimeException: Failed to start quarkus
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-2992/2/testReport/org.acme.orderpicking.solver/OrderPickingConstraintProviderTest/minimizeDistanceFromLastTrolleyStepToPathOrigin/">org.acme.orderpicking.solver.OrderPickingConstraintProviderTest.minimizeDistanceFromLastTrolleyStepToPathOrigin</a></summary>
java.lang.RuntimeException: Failed to start quarkus
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-2992/2/testReport/org.acme.vaccinationscheduler.solver/VaccinationScheduleConstraintProviderTest/requiredVaccinationCenter/">org.acme.vaccinationscheduler.solver.VaccinationScheduleConstraintProviderTest.requiredVaccinationCenter</a></summary>
java.lang.RuntimeException: Failed to start quarkus
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-2992/2/testReport/org.optaplanner.benchmark.quarkus/OptaPlannerBenchmarkProcessorBenchmarkConfigTest/___/">org.optaplanner.benchmark.quarkus.OptaPlannerBenchmarkProcessorBenchmarkConfigTest.(?)</a></summary>
java.lang.RuntimeException: Failed to start quarkus
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-2992/2/testReport/org.optaplanner.benchmark.quarkus/OptaPlannerBenchmarkProcessorEmptyAppWithInjectionTest/___/">org.optaplanner.benchmark.quarkus.OptaPlannerBenchmarkProcessorEmptyAppWithInjectionTest.(?)</a></summary>
java.lang.RuntimeException: Failed to start quarkus
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-2992/2/testReport/org.optaplanner.benchmark.quarkus/OptaPlannerBenchmarkProcessorInheritedSolverBenchmarkTest/___/">org.optaplanner.benchmark.quarkus.OptaPlannerBenchmarkProcessorInheritedSolverBenchmarkTest.(?)</a></summary>
java.lang.RuntimeException: Failed to start quarkus
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-2992/2/testReport/org.optaplanner.benchmark.quarkus/OptaPlannerBenchmarkProcessorMissingSpentLimitPerBenchmarkTest/___/">org.optaplanner.benchmark.quarkus.OptaPlannerBenchmarkProcessorMissingSpentLimitPerBenchmarkTest.(?)</a></summary>
java.lang.RuntimeException: Failed to start quarkus
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-2992/2/testReport/org.optaplanner.benchmark.quarkus/OptaPlannerBenchmarkProcessorMissingSpentLimitTest/___/">org.optaplanner.benchmark.quarkus.OptaPlannerBenchmarkProcessorMissingSpentLimitTest.(?)</a></summary>
java.lang.RuntimeException: Failed to start quarkus
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-2992/2/testReport/org.optaplanner.benchmark.quarkus/OptaPlannerBenchmarkProcessorNoBenchmarkConfigTest/___/">org.optaplanner.benchmark.quarkus.OptaPlannerBenchmarkProcessorNoBenchmarkConfigTest.(?)</a></summary>
java.lang.RuntimeException: Failed to start quarkus
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-2992/2/testReport/org.optaplanner.benchmark.quarkus/OptaPlannerBenchmarkProcessorPhasesTest/___/">org.optaplanner.benchmark.quarkus.OptaPlannerBenchmarkProcessorPhasesTest.(?)</a></summary>
java.lang.RuntimeException: Failed to start quarkus
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-2992/2/testReport/org.optaplanner.quarkus.benchmark.it/OptaPlannerBenchmarkTestResourceTest/benchmark/">org.optaplanner.quarkus.benchmark.it.OptaPlannerBenchmarkTestResourceTest.benchmark</a></summary>
java.lang.RuntimeException: Failed to start quarkus
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-2992/2/testReport/org.optaplanner.quarkus/OptaPlannerProcessorEmptyAppTest/___/">org.optaplanner.quarkus.OptaPlannerProcessorEmptyAppTest.(?)</a></summary>
java.lang.RuntimeException: Failed to start quarkus
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-2992/2/testReport/org.optaplanner.quarkus/OptaPlannerProcessorInterfaceEntityTest/___/">org.optaplanner.quarkus.OptaPlannerProcessorInterfaceEntityTest.(?)</a></summary>
java.lang.RuntimeException: Failed to start quarkus
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-2992/2/testReport/org.optaplanner.quarkus/OptaPlannerProcessorXMLDefaultTest/___/">org.optaplanner.quarkus.OptaPlannerProcessorXMLDefaultTest.(?)</a></summary>
java.lang.RuntimeException: Failed to start quarkus
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-2992/2/testReport/org.optaplanner.quarkus.verifier/OptaPlannerConstraintVerifierBavetStreamImplTest/___/">org.optaplanner.quarkus.verifier.OptaPlannerConstraintVerifierBavetStreamImplTest.(?)</a></summary>
java.lang.RuntimeException: Failed to start quarkus
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-2992/2/testReport/org.optaplanner.quarkus.it.devui/OptaPlannerDevUITest/testModelPage/">org.optaplanner.quarkus.it.devui.OptaPlannerDevUITest.testModelPage</a></summary>
java.lang.RuntimeException: Failed to start quarkus
</details>

**Comment by lucamolteni** [comment]
> @lucamolteni do you know please if optaplanner-quickstarts support JDK 17?

yes it does https://www.optaplanner.org/docs/optaplanner/latest/release-notes/release-notes.html#_compatible_with_jdk_19

**Comment by lucamolteni** [comment]
There seem to be some concurrency problem while binding addresses

```
Caused by: java.lang.RuntimeException: Unable to start HTTP server
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder.doServerStart(VertxHttpRecorder.java:846)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder.startServer(VertxHttpRecorder.java:339)
	at io.quarkus.deployment.steps.VertxHttpProcessor$openSocket189362710.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.VertxHttpProcessor$openSocket189362710.deploy(Unknown Source)
	... 53 more
Caused by: java.util.concurrent.ExecutionException: io.quarkus.runtime.QuarkusBindException: Port(s) already bound: 8081: Address already in use
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder.doServerStart(VertxHttpRecorder.java:773)
	... 56 more
```

**Comment by jstastny-cz** [comment]
@lucamolteni missing network=host in config, I've probably forgotten to put in optaplanner and drools config files, like it is for kogito-pipelines: https://github.com/apache/incubator-kie-drools/blob/main/.ci/jenkins/config/branch.yaml#L102

**Comment by jstastny-cz** [comment]
@lucamolteni ah, for PR checks we're currently managing through: https://github.com/apache/incubator-kie-kogito-pipelines/blob/main/dsl/scripts/pr_check.groovy#L9 ..... so not sure what happened in the run.

**Comment by baldimir** [comment]
Added fixes for the fullProfile - javadoc and sources jars generation.

**Review by jstastny-cz — APPROVED** [review]
LGTM.

**Comment by baldimir** [comment]
PR check is failing, because one quickstart needs JDK 17. Currently the PR check runs with JDK 11. It will be fixed in the future by splitting the quickstarts check to a separate one.

**Pull request merged**
