### PR TITLE
[10.0.x] NO-ISSUE: Disable generate-code-tests goal and fixes for the release job

### PR DESCRIPTION
**Pull request by rodrigonull**

### CODE REVIEW

**Review by baldimir — APPROVED** [review]

**Review by porcelli — APPROVED** [review]
this has been problematic for the release, root cause should be investigated for upcoming releases... 

however we believe this shouldn't be a blocker for the release

**Comment by tiagobento** [comment]
Can we please file an issue on `kie-issues` so we don't forget that we had to do this? We can continue the conversations there on what's the proper solution.

**Comment by tiagobento** [comment]
@rodrigonull ^

**Comment by rodrigonull** [comment]
Issue: https://github.com/apache/incubator-kie-issues/issues/1452

**Pull request merged**
