### PR TITLE
[10.0.x] kie-issues#1397: Adjust release pipelines for the Apache 10 release

### PR DESCRIPTION
**Pull request by rodrigonull**
Part of: https://github.com/apache/incubator-kie-issues/issues/1397

### CODE REVIEW

**Comment by kie-ci3** [comment]
**PR job** `#1` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-optaplanner/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-optaplanner -u https://github.com/apache/incubator-kie-optaplanner/pull/3111 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-3111/1/display/redirect

**Test results:**
- PASSED: 4902
- FAILED: 13

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-3111/1/testReport/org.acme.schooltimetabling/TimeTableMessagingHandlerTest/solvingThrowsException/">org.acme.schooltimetabling.TimeTableMessagingHandlerTest.solvingThrowsException</a></summary>
java.lang.NoClassDefFoundError: io/quarkus/devui/spi/page/PageBuilder
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-3111/1/testReport/org.acme.schooltimetabling.solver/TimeTableBenchmarkTest/PR_check___Build_projects___benchmark/">PR check / Build projects / org.acme.schooltimetabling.solver.TimeTableBenchmarkTest.benchmark</a></summary>
jakarta/xml/bind/JAXBException
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-3111/1/testReport/org.acme.kotlin.schooltimetabling.rest/TimeTableResourceTest/solveDemoDataUntilFeasible/">org.acme.kotlin.schooltimetabling.rest.TimeTableResourceTest.solveDemoDataUntilFeasible</a></summary>
java.lang.NoClassDefFoundError: io/quarkus/devui/spi/page/PageBuilder
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-3111/1/testReport/org.acme.demoapp.rest/DemoDataResourceTest/createTimeTable/">org.acme.demoapp.rest.DemoDataResourceTest.createTimeTable</a></summary>
java.lang.NoClassDefFoundError: io/quarkus/devui/spi/page/PageBuilder
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-3111/1/testReport/org.acme.schooltimetabling.messaging/MessageHandlerTest/incorrectSolutionClass_respondsWithError/">org.acme.schooltimetabling.messaging.MessageHandlerTest.incorrectSolutionClass_respondsWithError</a></summary>
java.lang.NoClassDefFoundError: io/quarkus/devui/spi/page/PageBuilder
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-3111/1/testReport/org.acme.callcenter.solver/CallCenterConstraintProviderTest/noRequiredSkillMissing/">org.acme.callcenter.solver.CallCenterConstraintProviderTest.noRequiredSkillMissing</a></summary>
java.lang.NoClassDefFoundError: io/quarkus/devui/spi/page/PageBuilder
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-3111/1/testReport/org.acme.employeescheduling.rest/EmployeeScheduleResourceTest/solveDemoDataUntilFeasible/">org.acme.employeescheduling.rest.EmployeeScheduleResourceTest.solveDemoDataUntilFeasible</a></summary>
java.lang.NoClassDefFoundError: io/quarkus/devui/spi/page/PageBuilder
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-3111/1/testReport/org.acme.facilitylocation.solver/FacilityLocationConstraintProviderTest/no_penalty_when_consumer_not_assigned/">org.acme.facilitylocation.solver.FacilityLocationConstraintProviderTest.no_penalty_when_consumer_not_assigned</a></summary>
java.lang.NoClassDefFoundError: io/quarkus/devui/spi/page/PageBuilder
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-3111/1/testReport/org.acme.maintenancescheduling.rest/MaintenanceScheduleResourceTest/solveDemoDataUntilFeasible/">org.acme.maintenancescheduling.rest.MaintenanceScheduleResourceTest.solveDemoDataUntilFeasible</a></summary>
java.lang.NoClassDefFoundError: io/quarkus/devui/spi/page/PageBuilder
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-3111/1/testReport/org.acme.orderpicking.solver/OrderPickingConstraintProviderTest/minimizeDistanceFromLastTrolleyStepToPathOrigin/">org.acme.orderpicking.solver.OrderPickingConstraintProviderTest.minimizeDistanceFromLastTrolleyStepToPathOrigin</a></summary>
java.lang.NoClassDefFoundError: io/quarkus/devui/spi/page/PageBuilder
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-3111/1/testReport/org.acme.schooltimetabling.rest/LessonResourceTest/getAll/">org.acme.schooltimetabling.rest.LessonResourceTest.getAll</a></summary>
java.lang.NoClassDefFoundError: io/quarkus/devui/spi/page/PageBuilder
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-3111/1/testReport/org.acme.vaccinationscheduler.solver/VaccinationScheduleConstraintProviderTest/requiredVaccinationCenter/">org.acme.vaccinationscheduler.solver.VaccinationScheduleConstraintProviderTest.requiredVaccinationCenter</a></summary>
java.lang.NoClassDefFoundError: io/quarkus/devui/spi/page/PageBuilder
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-3111/1/testReport/org.acme.vehiclerouting.rest/SolverResourceTest/solve/">org.acme.vehiclerouting.rest.SolverResourceTest.solve</a></summary>
java.lang.NoClassDefFoundError: io/quarkus/devui/spi/page/PageBuilder
</details>

**Review by tkobayas — APPROVED** [review]
The PR errors seem to be the same as Paolo reported in dev ML "[REVIEW] [NOT OK] Current status for the optaplanner 10.x jobs". Probably @lucamolteni can help?

**Comment by lucamolteni** [comment]
> The PR errors seem to be the same as Paolo reported in dev ML "[REVIEW] [NOT OK] Current status for the optaplanner 10.x jobs". Probably @lucamolteni can help?

Yes these tests are taking from optaplanner-quickstarts and those should be taken from the 

> The PR errors seem to be the same as Paolo reported in dev ML "[REVIEW] [NOT OK] Current status for the optaplanner 10.x jobs". Probably @lucamolteni can help?

I've answered in the apache ML but I'll copy my answer here as well

Was the 10.0.x branch taken from 8 because of this mapping that wasn’t never updated? (I’ve created a PR for it)

https://github.com/apache/incubator-kie-optaplanner/pull/3112/files

Reading the log from this failing PR (https://github.com/apache/incubator-kie-optaplanner/pull/3111)

[2024-07-23T19:21:26.364Z] # Checkout summary
[2024-07-23T19:21:26.364Z] [INFO] [apache/incubator-kie-optaplanner]
[2024-07-23T19:21:26.364Z] [INFO] Project taken from apache/incubator-kie-optaplanner:10.0.x (Branch HEAD 26504a8aa1a1201a4f334687278bc6f5b6d01fc4)
[2024-07-23T19:21:26.364Z] [INFO] Merged rodrigonull/incubator-kie-optaplanner:adjust-release-jobs into branch 10.0.x
[2024-07-23T19:21:26.364Z] [INFO] [apache/incubator-kie-optaplanner-quickstarts]
[2024-07-23T19:21:26.365Z] [INFO] Project taken from apache/incubator-kie-optaplanner-quickstarts:10.0.x (Branch HEAD b690beadc53493fb132e8a93d0b9d269f5452fed)

I see that build-chain is taking the 10.0.x branch from optaplanner-quickstart, but as Toshiya already noticed, the 10.0.x branch was wrongly created (see https://github.com/apache/incubator-kie-optaplanner-quickstarts/commits/10.0.x the last commit before the bump is 0085584a74976b66d8f43c1155012773c52e3fe1 instead of 752f8be515cbd02d1fc130dda75adb6e99b0dca7

I’m not sure if this email alone can help, feel free to ping me on Zulip so that we can fix this

**Review by jstastny-cz — APPROVED** [review]
LGTM.

**Comment by kie-ci3** [comment]
**PR job** `#2` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-optaplanner/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-optaplanner -u https://github.com/apache/incubator-kie-optaplanner/pull/3111 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-3111/2/display/redirect

**Test results:**
- PASSED: 4902
- FAILED: 13

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-3111/2/testReport/org.acme.schooltimetabling/TimeTableMessagingHandlerTest/solvingThrowsException/">org.acme.schooltimetabling.TimeTableMessagingHandlerTest.solvingThrowsException</a></summary>
java.lang.NoClassDefFoundError: io/quarkus/devui/spi/page/PageBuilder
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-3111/2/testReport/org.acme.schooltimetabling.solver/TimeTableBenchmarkTest/PR_check___Build_projects___benchmark/">PR check / Build projects / org.acme.schooltimetabling.solver.TimeTableBenchmarkTest.benchmark</a></summary>
jakarta/xml/bind/JAXBException
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-3111/2/testReport/org.acme.kotlin.schooltimetabling.rest/TimeTableResourceTest/solveDemoDataUntilFeasible/">org.acme.kotlin.schooltimetabling.rest.TimeTableResourceTest.solveDemoDataUntilFeasible</a></summary>
java.lang.NoClassDefFoundError: io/quarkus/devui/spi/page/PageBuilder
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-3111/2/testReport/org.acme.demoapp.rest/DemoDataResourceTest/createTimeTable/">org.acme.demoapp.rest.DemoDataResourceTest.createTimeTable</a></summary>
java.lang.NoClassDefFoundError: io/quarkus/devui/spi/page/PageBuilder
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-3111/2/testReport/org.acme.schooltimetabling.messaging/MessageHandlerTest/incorrectSolutionClass_respondsWithError/">org.acme.schooltimetabling.messaging.MessageHandlerTest.incorrectSolutionClass_respondsWithError</a></summary>
java.lang.NoClassDefFoundError: io/quarkus/devui/spi/page/PageBuilder
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-3111/2/testReport/org.acme.callcenter.solver/CallCenterConstraintProviderTest/noRequiredSkillMissing/">org.acme.callcenter.solver.CallCenterConstraintProviderTest.noRequiredSkillMissing</a></summary>
java.lang.NoClassDefFoundError: io/quarkus/devui/spi/page/PageBuilder
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-3111/2/testReport/org.acme.employeescheduling.rest/EmployeeScheduleResourceTest/solveDemoDataUntilFeasible/">org.acme.employeescheduling.rest.EmployeeScheduleResourceTest.solveDemoDataUntilFeasible</a></summary>
java.lang.NoClassDefFoundError: io/quarkus/devui/spi/page/PageBuilder
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-3111/2/testReport/org.acme.facilitylocation.solver/FacilityLocationConstraintProviderTest/no_penalty_when_consumer_not_assigned/">org.acme.facilitylocation.solver.FacilityLocationConstraintProviderTest.no_penalty_when_consumer_not_assigned</a></summary>
java.lang.NoClassDefFoundError: io/quarkus/devui/spi/page/PageBuilder
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-3111/2/testReport/org.acme.maintenancescheduling.rest/MaintenanceScheduleResourceTest/solveDemoDataUntilFeasible/">org.acme.maintenancescheduling.rest.MaintenanceScheduleResourceTest.solveDemoDataUntilFeasible</a></summary>
java.lang.NoClassDefFoundError: io/quarkus/devui/spi/page/PageBuilder
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-3111/2/testReport/org.acme.orderpicking.solver/OrderPickingConstraintProviderTest/minimizeDistanceFromLastTrolleyStepToPathOrigin/">org.acme.orderpicking.solver.OrderPickingConstraintProviderTest.minimizeDistanceFromLastTrolleyStepToPathOrigin</a></summary>
java.lang.NoClassDefFoundError: io/quarkus/devui/spi/page/PageBuilder
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-3111/2/testReport/org.acme.schooltimetabling.rest/LessonResourceTest/getAll/">org.acme.schooltimetabling.rest.LessonResourceTest.getAll</a></summary>
java.lang.NoClassDefFoundError: io/quarkus/devui/spi/page/PageBuilder
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-3111/2/testReport/org.acme.vaccinationscheduler.solver/VaccinationScheduleConstraintProviderTest/requiredVaccinationCenter/">org.acme.vaccinationscheduler.solver.VaccinationScheduleConstraintProviderTest.requiredVaccinationCenter</a></summary>
java.lang.NoClassDefFoundError: io/quarkus/devui/spi/page/PageBuilder
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-3111/2/testReport/org.acme.vehiclerouting.rest/SolverResourceTest/solve/">org.acme.vehiclerouting.rest.SolverResourceTest.solve</a></summary>
java.lang.NoClassDefFoundError: io/quarkus/devui/spi/page/PageBuilder
</details>

**Pull request merged**
