### PR TITLE
Upgrade Optaplanner to Quarkus 3.8.0

### PR DESCRIPTION
**Pull request by lucamolteni**
Upgraded to Quarkus 3.8.0 LTS

- Removed org.drools.util.RemoveCommentsMain as with the new quarkus version is not useful anymore
- Backport of Timefold migration to new DevUI 2.0 see original commit: https://github.com/TimefoldAI/timefold-solver/commit/8d5864df897c56b0ccfaaffbbf14908f04db61f4#diff-8b943be542be64385a97ac89619e4bcb7be615cf84f1623acd89357e131226af
- Fix Optaplanner Operator, disabled SSA as with the current version of the code it's broken 

### JIRA

https://github.com/apache/incubator-kie-issues/issues/1021
https://github.com/apache/incubator-kie-issues/issues/958

### Checklist
- [ ] Documentation updated if applicable.
- [ ] Release notes updated if applicable.
- [ ] Upgrade recipe provided if applicable.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  please add comment: <b>Jenkins (re)run [optaplanner|optaplanner-quickstarts] tests</b>
  
- for a <b>full downstream build</b> 
  - for <b>jenkins</b> job: 
    please add comment: <b>Jenkins run fdb</b>
  - for <b>github actions</b> job: 
    add the label `run_fdb`

- for a <b>compile downstream build</b>  
  please add comment: <b>Jenkins run cdb</b>

- for a <b>full production downstream build</b>  
  please add comment: <b>Jenkins execute product fdb</b>

- for an <b>upstream build</b>  
  please add comment: <b>Jenkins run upstream</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [optaplanner|optaplanner-quickstarts] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [optaplanner|optaplanner-quickstarts] quarkus-branch</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [optaplanner|optaplanner-quickstarts] quarkus-lts</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [optaplanner|optaplanner-quickstarts] native</b>

- for <b>native lts checks</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins run native-lts</b>

- for a <b>specific native lts check</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins (re)run [optaplanner|optaplanner-quickstarts] native-lts</b>

</details>

### CI Status

 You can check OptaPlanner repositories CI status from [Chain Status webpage](https://apache.github.io/incubator-kie-optaplanner/).

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Comment by lucamolteni** [comment]
@yurloc  see this ^

**Comment by kie-ci3** [comment]
**PR job** `#1` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-optaplanner/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-optaplanner -u https://github.com/apache/incubator-kie-optaplanner/pull/3070 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-3070/1/display/redirect

**Test results:**
- PASSED: 4984
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/optaplanner/job/main/job/pullrequest_jobs/job/optaplanner-pr/job/PR-3070/1/testReport/org.optaplanner.quarkus.it.devui/OptaPlannerDevUITest/testConstraintsPage/">org.optaplanner.quarkus.it.devui.OptaPlannerDevUITest.testConstraintsPage</a></summary>
<br/>Expecting actual:<br/>  ["org.optaplanner.quarkus.it.devui.domain/Maximize value length","org.optaplanner.quarkus.it.devui.domain/Don't assign 2 entities the same value."]<br/>to contain exactly (and in same order):<br/>  ["org.optaplanner.quarkus.it.devui.domain/Don't assign 2 entities the same value.",<br/>    "org.optaplanner.quarkus.it.devui.domain/Maximize value length"]<br/>but there were differences at these indexes:<br/>  - element at index 0: expected ""org.optaplanner.quarkus.it.devui.domain/Don't assign 2 entities the same value."" but was ""org.optaplanner.quarkus.it.devui.domain/Maximize value length""<br/>  - element at index 1: expected ""org.optaplanner.quarkus.it.devui.domain/Maximize value length"" but was ""org.optaplanner.quarkus.it.devui.domain/Don't assign 2 entities the same value.""<br/>
</details>

**Review by yurloc — APPROVED** [review]
@lucamolteni LGTM. Would you mind also bumping Quarkus version to 3.8.0 in the quickstarts?

**Review by pefernan — APPROVED** [review]

**Comment by mareknovotny** [comment]
btw quarkus already released 3.8.3 https://quarkus.io/blog/quarkus-3-8-3-released, so i guess there should not be a big diff, but good to have the latest LTS one ;) WDYT? @lucamolteni

**Comment by lucamolteni** [comment]
@yurloc https://github.com/apache/incubator-kie-optaplanner-quickstarts/pull/627

**Comment by porcelli** [comment]
@lucamolteni mind bump quarkus to 3.8.3? btw: thank you for this!

**Comment by porcelli** [comment]
@lucamolteni had to make the following change local to make it build:

```diff
diff --git i/optaplanner-persistence/optaplanner-persistence-xstream/pom.xml w/optaplanner-persistence/optaplanner-persistence-xstream/pom.xml
index 8f65d97677..113de384d1 100644
--- i/optaplanner-persistence/optaplanner-persistence-xstream/pom.xml
+++ w/optaplanner-persistence/optaplanner-persistence-xstream/pom.xml
@@ -77,6 +77,11 @@
       <artifactId>graal-sdk</artifactId>
       <scope>provided</scope>
     </dependency>
+    <dependency>
+      <groupId>org.graalvm.sdk</groupId>
+      <artifactId>nativeimage</artifactId>
+      <scope>provided</scope>
+    </dependency>
     <!-- Testing -->
     <dependency>
       <groupId>org.junit.jupiter</groupId>
```

**Comment by yesamer** [comment]
@lucamolteni @porcelli I guess we can close this PR, that's right?

**Pull request closed without merging**
